steps:
  - name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -lc
      - |
        npm i -g pnpm
        pnpm install --frozen-lockfile
        pnpm run build
  - name: gcr.io/cloud-builders/gsutil
    args: ['-m', 'rsync', '-r', '-c', '-d', 'build/', 'gs://www.modiase.dev']
