steps:
  - name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -lc
      - |
        npm i -g pnpm
        pnpm install --frozen-lockfile
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        bash bin/deploy-site
