/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        secondary: 'var(--color-secondary)',
        accent: 'var(--color-accent)',
        light: 'var(--color-light)',
        lightest: 'var(--color-lightest)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--color-surface-alt)',
        'surface-transparent-10': 'var(--color-surface-transparent-10)',
        'surface-transparent-20': 'var(--color-surface-transparent-20)',
        'surface-transparent-30': 'var(--color-surface-transparent-30)',
        'surface-transparent-40': 'var(--color-surface-transparent-40)',
        'surface-transparent-50': 'var(--color-surface-transparent-50)',
        'surface-transparent-60': 'var(--color-surface-transparent-60)',
        'surface-transparent-70': 'var(--color-surface-transparent-70)',
        'surface-transparent-80': 'var(--color-surface-transparent-80)',
        'surface-transparent-90': 'var(--color-surface-transparent-90)',
        'surface-transparent-100': 'var(--color-surface-transparent-100)',
        'surface-transparent-alt-10': 'var(--color-surface-transparent-alt-10)',
        'surface-transparent-alt-20': 'var(--color-surface-transparent-alt-20)',
        'surface-transparent-alt-30': 'var(--color-surface-transparent-alt-30)',
        'surface-transparent-alt-40': 'var(--color-surface-transparent-alt-40)',
        'surface-transparent-alt-50': 'var(--color-surface-transparent-alt-50)',
        'surface-transparent-alt-60': 'var(--color-surface-transparent-alt-60)',
        'surface-transparent-alt-70': 'var(--color-surface-transparent-alt-70)',
        'surface-transparent-alt-80': 'var(--color-surface-transparent-alt-80)',
        'surface-transparent-alt-90': 'var(--color-surface-transparent-alt-90)',
        'surface-transparent-alt-100': 'var(--color-surface-transparent-alt-100)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-dark': 'var(--text-dark)',
        success: 'var(--color-success)',
        'success-bg': 'var(--color-success-bg)',
        'success-text': 'var(--color-success-text)',
        'success-border': 'var(--color-success-border)',
        error: 'var(--color-error)',
        'error-bg': 'var(--color-error-bg)',
        'error-text': 'var(--color-error-text)',
        'error-border': 'var(--color-error-border)',
        warning: 'var(--color-warning)',
        'warning-bg': 'var(--color-warning-bg)',
        'warning-text': 'var(--color-warning-text)',
        'warning-border': 'var(--color-warning-border)',
        white: 'var(--color-white)',
        disabled: 'var(--color-disabled)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        contrast: 'var(--color-contrast)',
        'link-active': 'var(--color-link-active)',
        'link-hover': 'var(--color-link-hover)',
      },
      fontFamily: {
        grotesk: ['Space Grotesk', 'Arial', 'Helvetica', 'sans-serif'],
        Lato: ['Lato', 'Arial', 'Helvetica', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
